### ISSUE TITLE
Problems with request. Socket read timed out

### ISSUE THREAD

**Issue by NanitSoft** [VKCOM/vk-java-sdk#134]
Прошу помощи. Примерно в 23:45 каждую ночь кидает эту ошибку. Адресс LongPoll и так обновляет каждый час, но постоянно проблема с этим сокетом.

2019-45-21 23:45:08.790 [Thread-3] ERROR com.vk.api.sdk.client.ApiRequest - Problems with request: https://lp.vk.com/wh70923065
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_191]
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_191]
    at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_191]
    at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_191]
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_191]
    at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_191]
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[?:1.8.0_191]
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) ~[?:1.8.0_191]
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_191]
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)

**Comment by NanitSoft** [comment]
Проблема была с интернетом на хосте. Тема закрыта
