### ISSUE TITLE
java.net.MalformedURLException: no protocol:

### ISSUE THREAD

**Issue by Maarchello** [VKCOM/vk-java-sdk#178]
При вызове ` client.wall().get(actor).ownerId(id).count(size).execute();` летит исключение:
```
com.vk.api.sdk.client.ApiRequest         : Invalid JSON: // тут JSON (проверил онлайн - он валидный)

com.google.gson.JsonSyntaxException: java.net.MalformedURLException: no protocol:
        at com.google.gson.Gson.fromJson(Gson.java:942) ~[gson-2.8.5.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:994) ~[gson-2.8.5.jar!/:na]
Caused by: java.net.MalformedURLException: no protocol:
        at java.net.URL.<init>(URL.java:600) ~[na:1.8.0_222]
        at java.net.URL.<init>(URL.java:497) ~[na:1.8.0_222]
        at java.net.URL.<init>(URL.java:446) ~[na:1.8.0_222]
com.vk.api.sdk.exceptions.ClientException: Can't parse json response
        at com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104)
```

Проблема возникает когда поле url объекта Audio пустое (не null, а именно пустая строка)

**Comment by Dokusei** [comment]
Какая версия sdk? У меня норм все
![11111111](https://user-images.githubusercontent.com/48102566/66675213-8b0d3600-ec6d-11e9-9d41-37194b9bb167.png)

**Comment by Maarchello** [comment]
@Dokusei проблема возникает в версии 1.0.6 (0.5.12 работает норм). При этом возникает не всегда - если поле url заполнено, то исключение не летит

**Comment by prokhorovalexey** [comment]
Это достаточно известное поведение. Достаточно погуглить "com.google.gson.JsonSyntaxException: java.net.MalformedURLException: no protocol:"

**Comment by aotd1** [comment]
В v1.0.7 поправили URL на URI, теперь должно работать
