### ISSUE TITLE
java.net.URISyntaxException в поле com.vk.api.sdk.objects.base.Link.url

### ISSUE THREAD

**Issue by merfemor** [VKCOM/vk-java-sdk#237]
Падает со следующим исключением при вызове wall.search:
```
java.net.URISyntaxException: Illegal character in query at index 72: http://career.itmo.ru/?utm_source=vkontakte&utm_medium=cpc&utm_campaign={campaign_id}&utm_content={ad_id}💡
com.google.gson.JsonIOException: java.net.URISyntaxException: Illegal character in query at index 72: http://career.itmo.ru/?utm_source=vkontakte&utm_medium=cpc&utm_campaign={campaign_id}&utm_content={ad_id}💡
	at com.google.gson.internal.bind.TypeAdapters$22.read(TypeAdapters.java:513)
	at com.google.gson.internal.bind.TypeAdapters$22.read(TypeAdapters.java:502)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)

```
Очевидно, не парсится из-за символа '{' в uri. Вот [ссылка на пост](https://vk.com/itmostudents?w=wall-2499902_31064), в котором эта ссылка.
Хотелось бы увидеть фикс для этого. Вероятно просто использовать String вместо URI для поля.

**Comment by aotd1** [comment]
Fixed in [vk-api-schema v5.131.112](https://github.com/VKCOM/vk-api-schema/releases/tag/v5.131.112)
