### ISSUE TITLE
API error com.vk.api.sdk.exceptions.ApiAuthException: User authorization failed (5)

### ISSUE THREAD

**Issue by LymonMine** [VKCOM/vk-java-sdk#253]
API error
com.vk.api.sdk.exceptions.ApiAuthException: User authorization failed (5): User authorization failed: invalid session.
    at com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:17)
    at com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104)
    at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79)
    at com.vk.api.sdk.callback.longpoll.CallbackApiLongPoll.getLongPollServer(CallbackApiLongPoll.java:79)
    at com.vk.api.sdk.callback.longpoll.CallbackApiLongPoll.run(CallbackApiLongPoll.java:60)
Пробую авторизоваться группой, использовал id группы из поста и из "club_id", токен брал из работа с api - ключ доступа. Всё равно ошибка. Какое решение проблемы может быть?

**Comment by LymonMine** [comment]
Вот как проходит авторизация. 
`TransportClient transportClient = new HttpTransportClient();
        VkApiClient vk = new VkApiClient(transportClient);
        GroupActor actor = new GroupActor(config.getInt("vk-settings.groupid"), config.getString("vk-settings.groupToken"));`

**Comment by LymonMine** [comment]
решено
