### ISSUE TITLE
Ошибка при инициализации java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by doverchivost** [VKCOM/vk-java-sdk#260]
**`
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean org.apache.commons.lang3.StringUtils.isNoneEmpty(java.lang.CharSequence[])'
	at com.vk.api.sdk.client.VkApiClient.<init>(VkApiClient.java:68)
	at com.vk.api.sdk.client.VkApiClient.<init>(VkApiClient.java:60)
	at Bot.main(Bot.java:42)
`**

42 строка:
`vk = new VkApiClient(transportClient);`

**Comment by doverchivost** [comment]
Ошибка в том, что библиотека instagram4j использует "commons-lang3-3.1", а вк "commons-lang3-3.6". Удалила первую, теперь все работает
