### ISSUE TITLE
Gson exception

### ISSUE THREAD

**Issue by TrueGameover** [VKCOM/vk-java-sdk#46]
`.oauth().groupAuthorizationCodeFlow(APPLICATION_ID, APPLICATION_SECRET, groupRedirectUrl, code).execute()`
```
IllegalArgumentException occurred : @JsonAdapter value must be TypeAdapter or TypeAdapterFactory reference.

play.exceptions.JavaExecutionException: @JsonAdapter value must be TypeAdapter or TypeAdapterFactory reference.

Caused by: java.lang.IllegalArgumentException: @JsonAdapter value must be TypeAdapter or TypeAdapterFactory reference.
	at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.getTypeAdapter(JsonAdapterAnnotationTypeAdapterFactory.java:64)
	at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.create(JsonAdapterAnnotationTypeAdapterFactory.java:47)
	at com.google.gson.Gson.getAdapter(Gson.java:416)
	at com.google.gson.Gson.fromJson(Gson.java:878)
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:85)
```

**Comment by TrueGameover** [comment]
Извиняюсь, play 1.4.3 перегружал зависимость версией 2.6.2 из-за чего происходил эксепшен.
