### ISSUE TITLE
Ошибка "Invalid JSON" при запросе постов со стены

### ISSUE THREAD

**Issue by dennydenny** [VKCOM/vk-java-sdk#62]
Добрый день!
При проверке выполнения issue #60 обнаружил, что при ранее корректно работавшем вызове теперь возникает ошибка. 
Вызов SDK:
`GetResponse response = vk.wall().get(actor).ownerId(owner).execute();`

Ошибка возникает при вызове кода в com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:85).

Сама ошибка (выжимка):
`2017-04-08 17:33:24 INFO  HttpTransportClient:158 - Request: https://api.vk.com/method/wall.get		113
2017-04-08 17:33:24 ERROR ApiRequest:87 - Invalid JSON: {"тут_полный_ответный_JSON}
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.items[0].views`

Судя по всему, ошибка возникает из-за того, что в атрибуте views ответного JSON находится не число, а вложенный атрибут count, который и содержит число просмотров.

Также отмечу, что, например, для получения числа лайков из объекта WallpostFull, требуется выполнить getLikes().getCount(), а для получения просмотров сейчас доступен только метод getViews() (без getCount()). Вызвать getViews().getCount() сейчас невозможно.

Ошибка (полностью):
`2017-04-08 17:33:24 INFO  HttpTransportClient:158 - Request: https://api.vk.com/method/wall.get		113
2017-04-08 17:33:24 ERROR ApiRequest:87 - Invalid JSON: {"тут_полный_ответный_JSON}
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.items[0].views
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:85) [sdk-0.5.0.jar:?]
	at тут_мои_классы
Caused by: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.items[0].views
	at com.google.gson.internal.bind.JsonTreeReader.nextInt(JsonTreeReader.java:241) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:243) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:235) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:?]
	... 11 more`

**Comment by tsivarev** [comment]
Fixed
