### ISSUE TITLE
Unknown (28): Application authorization failed: access_token has expired

### ISSUE THREAD

**Issue by AntonYurchenko** [VKCOM/vk-java-sdk#73]
Добрый день, написал вопрос в поддержку VK, меня отправили сюда, сказали нужна помощь гуру :-)
Суть проблемы:
Создал приложение (id 6116692). Пытаюсь авторизироваться с использованием сервисного ключа, как показано в документации, в ответ получаю: Application authorization failed: access_token has expired.

Использую SDK "com.vk.api" % "sdk" % "0.5.6"

Пример кода (Scala):

package ru.restream.vkexample

import com.vk.api.sdk.client.{Lang, VkApiClient}
import com.vk.api.sdk.client.actors.ServiceActor
import com.vk.api.sdk.httpclient.HttpTransportClient
import com.vk.api.sdk.queries.users.UserField

object Main extends App {

val APP_ID = 6116692 //из настроек приложения
val CLIENT_SECRET = "MBY8G8U41uyD0OszSrbD" //из настроек приложения

val transportClient = HttpTransportClient.getInstance()
val vk = new VkApiClient(transportClient)

val authRequest = vk.oauth
.serviceClientCredentialsFlow(APP_ID,CLIENT_SECRET)
.execute

val serviceActor = new ServiceActor(APP_ID,CLIENT_SECRET,authRequest.getAccessToken)

val users = vk.users
.get(serviceActor)
.userIds("1")
.fields(UserField.VERIFIED, UserField.SEX)
.lang(Lang.EN)
.execute

}

Консоль выводит:
Exception in thread "main" com.vk.api.sdk.exceptions.ApiException: Unknown (28): Application authorization failed: access_token has expired.
at com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:257)
at com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:91)
at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:66)
at ru.restream.vkexample.Main$.delayedEndpoint$ru$restream$vkexample$Main$1(Main.scala:29)
at ru.restream.vkexample.Main$delayedInit$body.apply(Main.scala:11)
at scala.Function0.apply$mcV$sp(Function0.scala:34)
at scala.Function0.apply$mcV$sp$(Function0.scala:34)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
at scala.App.$anonfun$main$1$adapted(App.scala:76)
at scala.collection.immutable.List.foreach(List.scala:378)
at scala.App.main(App.scala:76)
at scala.App.main$(App.scala:74)
at ru.restream.vkexample.Main$.main(Main.scala:11)
at ru.restream.vkexample.Main.main(Main.scala)

Что делаю не так?
Спасибо

**Comment by tsivarev** [comment]
Для использования обычных методов, не secure.*, нужно использовать "Сервисный ключ доступа" из панели управления вашего приложения. Больше прочитать про это можно здесь: https://vk.com/dev/service_token

**Comment by AntonYurchenko** [comment]
Спасибо, запрос отработал. Не могу понять, в результате получаю null
val users = vk.users
    .get(serviceActor)
    .userIds("210700286")
    .fields(UserField.ABOUT)
    .lang(Lang.EN)
    .execute

Возвращает [UserXtrCounters{counters=**null**}]

**Comment by mohaxspb** [comment]
Поясню для примера кодом:

```
        val transportClient = HttpTransportClient()
        val vk = VkApiClient(transportClient)

        val actor = ServiceActor(vkAppId, vkClientSecret, vkServiceAccessKey)

        val getResponse = vk.wall().get(actor)
                .ownerId(1)
                .count(100)
                .offset(5)
                .filter(WallGetFilter.OWNER)
                .execute()
```

**Comment by franrolando** [comment]
Worked for me! Thank you @mohaxspb
